-- Oracle SQL DDL Script for FreeLanceFlow
-- Target: Oracle Database 12c or higher (using IDENTITY columns)

-- Users Table
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    phone VARCHAR2(15) UNIQUE,
    profile_pic VARCHAR2(255),
    role VARCHAR2(20) DEFAULT 'client' CHECK (role IN ('freelancer', 'client', 'admin')),
    is_verified NUMBER(1) DEFAULT 0,
    is_active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Freelancer Profiles
CREATE TABLE freelancer_profiles (
    profile_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER UNIQUE,
    bio CLOB,
    hourly_rate NUMBER(8, 2),
    experience_years NUMBER DEFAULT 0,
    portfolio_url VARCHAR2(255),
    github_url VARCHAR2(255),
    linkedin_url VARCHAR2(255),
    availability VARCHAR2(20) DEFAULT 'available' CHECK (availability IN ('available', 'busy', 'not_available')),
    total_earned NUMBER(12, 2) DEFAULT 0.00,
    avg_rating NUMBER(3, 2) DEFAULT 0.00,
    total_projects NUMBER DEFAULT 0,
    CONSTRAINT fk_freelancer_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Skills
CREATE TABLE skills (
    skill_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(80) UNIQUE NOT NULL,
    category VARCHAR2(80)
);

-- Freelancer Skills
CREATE TABLE freelancer_skills (
    freelancer_skill_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    skill_id NUMBER,
    proficiency VARCHAR2(20) DEFAULT 'intermediate' CHECK (proficiency IN ('beginner', 'intermediate', 'expert')),
    CONSTRAINT fk_skill_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_skill_ref FOREIGN KEY (skill_id) REFERENCES skills(skill_id),
    CONSTRAINT unique_user_skill UNIQUE (user_id, skill_id)
);

-- Projects
CREATE TABLE projects (
    project_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id NUMBER,
    title VARCHAR2(150) NOT NULL,
    description CLOB NOT NULL,
    budget_min NUMBER(10, 2),
    budget_max NUMBER(10, 2),
    deadline DATE,
    project_type VARCHAR2(20) NOT NULL CHECK (project_type IN ('fixed', 'hourly')),
    status VARCHAR2(20) DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'completed', 'cancelled')),
    visibility VARCHAR2(20) DEFAULT 'public' CHECK (visibility IN ('public', 'invite_only')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_project_client FOREIGN KEY (client_id) REFERENCES users(user_id)
);

-- Project Required Skills
CREATE TABLE project_required_skills (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id NUMBER,
    skill_id NUMBER,
    CONSTRAINT fk_req_project FOREIGN KEY (project_id) REFERENCES projects(project_id),
    CONSTRAINT fk_req_skill FOREIGN KEY (skill_id) REFERENCES skills(skill_id)
);

-- Proposals
CREATE TABLE proposals (
    proposal_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id NUMBER,
    freelancer_id NUMBER,
    cover_letter CLOB NOT NULL,
    bid_amount NUMBER(10, 2) NOT NULL,
    estimated_days NUMBER,
    status VARCHAR2(20) DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected', 'withdrawn')),
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prop_project FOREIGN KEY (project_id) REFERENCES projects(project_id),
    CONSTRAINT fk_prop_freelancer FOREIGN KEY (freelancer_id) REFERENCES users(user_id),
    CONSTRAINT unique_project_freelancer UNIQUE (project_id, freelancer_id)
);

-- Contracts
CREATE TABLE contracts (
    contract_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id NUMBER UNIQUE,
    project_id NUMBER,
    client_id NUMBER,
    freelancer_id NUMBER,
    agreed_amount NUMBER(10, 2) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    status VARCHAR2(20) DEFAULT 'active' CHECK (status IN ('active', 'paused', 'completed', 'terminated')),
    terms CLOB,
    signed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cont_proposal FOREIGN KEY (proposal_id) REFERENCES proposals(proposal_id),
    CONSTRAINT fk_cont_project FOREIGN KEY (project_id) REFERENCES projects(project_id),
    CONSTRAINT fk_cont_client FOREIGN KEY (client_id) REFERENCES users(user_id),
    CONSTRAINT fk_cont_freelancer FOREIGN KEY (freelancer_id) REFERENCES users(user_id)
);

-- Milestones
CREATE TABLE milestones (
    milestone_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id NUMBER,
    title VARCHAR2(150) NOT NULL,
    description CLOB,
    amount NUMBER(10, 2) NOT NULL,
    due_date DATE,
    status VARCHAR2(20) DEFAULT 'pending' CHECK (status IN ('pending', 'submitted', 'approved', 'rejected')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mile_contract FOREIGN KEY (contract_id) REFERENCES contracts(contract_id)
);

-- Messages
CREATE TABLE messages (
    message_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id NUMBER,
    sender_id NUMBER,
    receiver_id NUMBER,
    content CLOB NOT NULL,
    is_read NUMBER(1) DEFAULT 0,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_msg_contract FOREIGN KEY (contract_id) REFERENCES contracts(contract_id),
    CONSTRAINT fk_msg_sender FOREIGN KEY (sender_id) REFERENCES users(user_id),
    CONSTRAINT fk_msg_receiver FOREIGN KEY (receiver_id) REFERENCES users(user_id)
);

-- Notifications
CREATE TABLE notifications (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    title VARCHAR2(120) NOT NULL,
    message CLOB NOT NULL,
    type VARCHAR2(20),
    is_read NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Indices for performance
CREATE INDEX idx_user_email ON users(email);
CREATE INDEX idx_project_status ON projects(status);
CREATE INDEX idx_msg_sender ON messages(sender_id);
CREATE INDEX idx_msg_receiver ON messages(receiver_id);
